### ISSUE TITLE
How to use fragments instead of changing only the pic in a single fragment

### ISSUE THREAD

**Issue by syedalinaqi** [Yalantis/Side-Menu.Android#10]
I was looking at the MainActivity.java and ContentFragment.java in the sample. I came to know that you use screenShotable for image changing and Animation. I Was Wondering that how can i use it in order to change Fragments. I Tried A bunch of techniques, but no use. So Can u plz tell me what I Should do. How do i change fragments On items click. It would be a great Help!!! plz,,,

**Comment by Apisov** [comment]
If question is still actual.
In MainActivity implemented ViewAnimatorListener.
There is onSwitch method where you can figure out what item of menu was clicked and replace fragment on a new one.

**Comment by syedalinaqi** [comment]
Thanks...
