### ISSUE TITLE
Compile failure in Android Studio 1.1

### ISSUE THREAD

**Issue by skywalkerlw** [Yalantis/Side-Menu.Android#11]
it's a little frustrated to see compile failure in Android Studio 1.1

![image](https://cloud.githubusercontent.com/assets/2090084/5958678/e0f0bbd6-a812-11e4-83f2-48304108317c.png)

**Comment by XhinLiang** [comment]
Glad to see this.
But , can you give the source code of the demo ? ( the better  For Eclipese
 )
See you.

2015-01-29 21:58 GMT+08:00 Liang Wang notifications@github.com:

**Comment by skywalkerlw** [comment]
just import your project into Android studio and I got above error

**Comment by hellworld** [comment]
I am meeting same problem with you!

**Comment by kotya341** [comment]
please check out this with gradle dependency I hope it can help you
