### ISSUE TITLE
Didn't find class "com.nineoldandroids.animation.ObjectAnimator

### ISSUE THREAD

**Issue by Ernest-su** [Yalantis/Side-Menu.Android#13]
when i switch menu,it cause Didn't find class "com.nineoldandroids.animation.ObjectAnimator exception

**Comment by Apisov** [comment]
Can you provide more details?
Is library CircularReveal downloaded completely? Can you find this class by yourself in you project? Tap "Shift" double times and type ObjectAnimator.
First of all: try clean and build project.

**Comment by TheBlusky** [comment]
Same here.
It's working fine on a Nexus 5 (Lolipop).
But "java.lang.NoClassDefFoundError: com.nineoldandroids.animation.ObjectAnimator" on Samsung S3 and Samsung S5 (Android 4)

**Comment by afaucogney** [comment]
Hello,

 I got the same error on a GalaxyS4 (no in Lolipop). I copy more or less the exemple, but I'm not able to switch between fragment.

```
java.lang.NoClassDefFoundError: com.nineoldandroids.animation.ObjectAnimator
        at io.codetail.animation.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:62)
        at fr.millezimu.app.extendedviewpager.Activity.MainActivity.replaceFragment(MainActivity.java:283)
```

I clean the projet
I have the class, but compiled as I imported just the lib. When I looked on the github source, it seems that there are a couple of ViewAnimationUtils that are version dependent...help would be welcome.

**Comment by longjunye** [comment]
add the nineoldandroids lib will works fine

**Comment by rubanraj54** [comment]
add the following line in to ur dependency. It will work.

compile 'com.nineoldandroids:library:2.4.+'
