### ISSUE TITLE
I find a problem in your library!

### ISSUE THREAD

**Issue by LittleAunt** [Yalantis/Side-Menu.Android#16]
When I click a menu item,then immediately left smooth before closed animation performed in the menu.
Then I can't left slide.

**Comment by Apisov** [comment]
Okay, we'll try to reproduce this and fix.

**Comment by kotya341** [comment]
@LittleAunt Can you please explain what do you mean "left slide"

**Comment by LittleAunt** [comment]
slide from left @kotya341
