### ISSUE TITLE
a problem "Only the original thread that created a view hierarchy can touch its views"

### ISSUE THREAD

**Issue by LittleAunt** [Yalantis/Side-Menu.Android#17]
When listview scroll,Screenshots will collapse.Due to the takeScreenShot function perform "containerView.draw(canvas);" in the child thread.

**Comment by Apisov** [comment]
Thanks for comment. We'll check it ASAP.

**Comment by kotya341** [comment]
Unfortunately we can't reproduce this crash
Can you please give us more details
