### ISSUE TITLE
Not getting reveal effect.

### ISSUE THREAD

**Issue by deepakrokz** [Yalantis/Side-Menu.Android#18]
When i tried this project in eclipse and run then its not showing reveal effect in lollipop running devices (Working in lower than lollipop) but from Android Studio its working fine for all api level . Please take a look at this issue.

**Comment by guilhermesgb** [comment]
I have the same problem - in my case, this is not working in KitKat!

**Comment by kotya341** [comment]
You found problem only with animation?
I think it can be animation lib problem
