### ISSUE TITLE
How can i change the drawer color?

### ISSUE THREAD

**Issue by JinSB** [Yalantis/Side-Menu.Android#21]
Hello

How can i change the drawer color? is there any interface? 
and where can i download the source code?

Thanks.

**Comment by kotya341** [comment]
You can download source code here in github :smile: 
To change drawer color you have to use this lib as com.android.library and change it manually

**Comment by brindakrishnaswamy** [comment]
I included this library in android app And when i changed the background color in menu_list_item.xml in layout folder to like below , But the color remains same dark blue? how to change the color of drawer image background to match action bar.

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/menu_item_container"
                android:layout_width="80dp"
                android:layout_height="80dp"
                android:clickable="true"
                android:background="@android:color/darker_gray">

    <ImageView
        android:id="@+id/menu_item_image"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"/>
</RelativeLayout>

**Comment by Silent-Night** [comment]
**Question #1**
On the side menu the icon sections have a big rectangle and im using small icons and it looks very odd to have the big rectangle with small icons. Is there anyway to adjust the size of those to make them smaller so it doesnt look as odd? If so how do I do this?

**Question #2**
I would also like to implement your context menu in the side menu app. Do all the files have to be added seperately such as the code from each section placed in the code for side menu? Can that be done? Or is the context menu seperate? Can they be combined? If so do you have an easy way to do it?

Thank you
