### ISSUE TITLE
How to switch fragments by view instead of bitmap? 

### ISSUE THREAD

**Issue by TindleWei** [Yalantis/Side-Menu.Android#22]
Your demo use a bitmap as Fragment content.  
The fragment must implements `ScreenShotable`, override `getBitmap()`  and `takeScreenShot()`. 
When animating, `ViewAnimator`  use `screenShotable.takeScreenShot()` to set the image as background.
So it need use a view as background to adapter more situation.
- I tried to use the backgound color from switch fragment as the revealing backgound,  but the effect is not so well.
- I tried to set styles to make activity's backgourd transparent, but not worked.  

How could I do to use view as swich backgound instead of bitmap.

**Comment by TeeRawk** [comment]
Hello,thank's for the comment . Sorry but, it's currently not avalible to set an actual view as a background.
