### ISSUE TITLE
Right Sliding

### ISSUE THREAD

**Issue by ahmedbenahmed** [Yalantis/Side-Menu.Android#26]
How to change it to slide from the right

**Comment by TeeRawk** [comment]
Well ,first of all you need to change the gravity of drawerLayout to RIGHT. Then to allow calling side menu on navigation button you should call toolbar.  
 toolbar.setNavigationOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(drawerLayout.isDrawerOpen(Gravity.RIGHT)){
                    drawerLayout.closeDrawer(Gravity.RIGHT);
                }else
                {
                    drawerLayout.openDrawer(Gravity.RIGHT);
                }
            }
        });

that's will doo the trick , you sould be able to call the side menu as by  draging it from right, and by clicking the navigation button
