### ISSUE TITLE
Not able to handle events like button click 

### ISSUE THREAD

**Issue by vinayakahampapattanada** [Yalantis/Side-Menu.Android#28]
i am not able achieve event handling in fragments

**Comment by vinayakahampapattanada** [comment]
Can you please tell me how to achieve event handling

**Comment by pawlo2102** [comment]
Try to handle onOptionsItemSelected(MenuItem item) in your Activity

**Comment by ademcan25** [comment]
Handle with ScreenShotable onSwitch(Resourceble slideMenuItem, ... method.You can use slideMenuItem name for the which button click.
