### ISSUE TITLE
How to use between fragments

### ISSUE THREAD

**Issue by mitab86** [Yalantis/Side-Menu.Android#33]
I really like this side menu library but don't have idea how to use it..can someone tell me step by step process so i could use it to navigate between different fragments.??Thanks in advance

**Comment by TeeRawk** [comment]
Hello, if u tried to use the sample project you should see the method called onSwitch.
There you can use this construction for navigating between fragments 
switch (slideMenuItem.getName()) {
            case ContentFragment.CLOSE:
                return screenShotable;
            case ContentFragment.MOVIE:
                 getSupportFragmentManager().beginTransaction()
                    .replace(new SomeFragment())
                    .commit();
break;
            default:
                return replaceFragment(screenShotable, position);
        }
Hope it helps.

**Comment by mitab86** [comment]
Thanks for the knowledge..do you mean its like using switch function in navigation drawer?

**Comment by TeeRawk** [comment]
Yes, basically it is.  you just catch the case when the menu with specific id is clicked and then, u replacing the fragment.

**Comment by suarkadipa** [comment]
could you please write the complete code?

**Comment by nehachauhan2210** [comment]
How to open two fragments in side menu

**Comment by mohamedebrahim96** [comment]
i also need the complete code please share it ?

**Comment by Kuber04** [comment]
Hi Could Please provide the Fragment Code...It would be highly appreciated 
Thanks

**Comment by mohamedebrahim96** [comment]
![App](https://user-images.githubusercontent.com/16405013/29244143-68394f68-7fb1-11e7-9864-dec88cd42660.jpg)

=====================================
This is my fragment code - full project on github
https://github.com/mohamedebrahim96/Whos-in-Space

===========================================
you may also see the live version on google play 
https://play.google.com/store/apps/details?id=com.vacuum.app.whoisinspace

**Comment by Kuber04** [comment]
Thank you so much sir.
