### ISSUE TITLE
Using deprecated ActionBarActivity

### ISSUE THREAD

**Issue by Salma90** [Yalantis/Side-Menu.Android#35]
I want to use the library with AppCompatActivity but the ViewAnimator accept ActionBarActivity
how can i solve the deprecation problem

**Comment by Farasy** [comment]
Hi Salma, change ViewAnimator to:

`public ViewAnimator(Activity activity, List<T> items, final DrawerLayout drawerLayout, ViewAnimatorListener animatorListener){
        this.activity = activity;
        this.list = items;
        this.drawerLayout = drawerLayout;
        this.animatorListener = animatorListener;
    }`
