### ISSUE TITLE
Failed to resolve: com.yalantis:ucrop:1.3.+

### ISSUE THREAD

**Issue by HosseinKurd** [Yalantis/Side-Menu.Android#38]
When I add `compile 'com.yalantis:ucrop:1.3.+'` to project it show error 

Error:(30, 13) Failed to resolve: com.yalantis:ucrop:1.3.+

![capture](https://cloud.githubusercontent.com/assets/7655247/13547773/09f5f9f2-e2f4-11e5-8031-4f5cc8b7e967.PNG)

i can not resolve it !
how to fix it ?

**Comment by edBaev** [comment]
Could you please leave an issue here - https://github.com/Yalantis/uCrop
