### ISSUE TITLE
can't use with gradle?

### ISSUE THREAD

**Issue by coolegos** [Yalantis/Side-Menu.Android#4]

**Comment by alexzaitsev** [comment]
Thank you for good question. We are working on this. Check for updates.

**Comment by satabd** [comment]
Thank you for sharing this beautiful side menu, but I received a msg at Cradle
Error:A problem occurred configuring project ':app'.

> Cannot evaluate module circualreveal : Configuration with name 'default' not found.

**Comment by kotya341** [comment]
I think it's can help you 
http://stackoverflow.com/a/24461710
and be sure that you use gradle version 2.2.1

**Comment by coolegos** [comment]
I see.thx
