### ISSUE TITLE
Cant find R package

### ISSUE THREAD

**Issue by mehdinewdesign** [Yalantis/Side-Menu.Android#42]
Hi
when I open your side-Menu the R package is not identify with android studio.
import yalantis.com.sidemenu.R;

may you create a step by step article for learning about your Side-Menu sample?

I'm new in android programming , and this is my Email : Mahdi.Shabani@hotmail.com

Thank you so much.

**Comment by dmytroDenysenko** [comment]
Hi @mehdinewdesign 
R package can not be found if project is not built with gradle build tools. Are you sure you imported it properly and set gradle up? Do you still experience this issue?

**Comment by mehdinewdesign** [comment]
@cleanOK 
I remove this error...

Thanks...

**Comment by dmytroDenysenko** [comment]
@mehdinewdesign have a nice day
