### ISSUE TITLE
How to convert Uri to R drawable ? 

### ISSUE THREAD

**Issue by giangtranml** [Yalantis/Side-Menu.Android#44]
I have a Uri,file that stored in device. How can i use it into SlideMenuItem (R.drawable....) ?

**Comment by fengkeyi** [comment]
Bitmap bitmap = BitmapFactory.decodeFile("path"); is that can help you?

**Comment by giangtranml** [comment]
it's not Bitmap, the second parameter of SlideMenuItem must int(resource drawable, it's like R.drawable.ic_action_name). Any suggestion ??

**Comment by TeeRawk** [comment]
Hello @lingboo, for now there is no such functional, we'll consider it for the next version.
