### ISSUE TITLE
Side menu

### ISSUE THREAD

**Issue by nehachauhan2210** [Yalantis/Side-Menu.Android#49]
How to open two fragments in side menu

**Comment by TeeRawk** [comment]
Hi, @nehachauhan2210 , what do you mean by opening two fragments  ? You want to  show them on one activity ?

**Comment by nehachauhan2210** [comment]
Yes

**Comment by TeeRawk** [comment]
First of all, make sepparate containers for fragment in your activity layout, it can be to FrameLayouts for example.
Ok so as you can see in example ,there is a replace fragment method. There is a line in it 
`getSupportFragmentManager().beginTransaction().replace(R.id.content_frame, contentFragment).commit();`
R.id.content_frame is your first fragment container. And the content fragment in there is your first fragment  So basicaly in onSwitch method , you can call replaceFragment () , and then `getSupportFragmentManager().beginTransaction().replace(R.id.second_fragment_container, second fragment).commit();`

**Comment by nehachauhan2210** [comment]
Thanks

**Comment by fnokeke** [comment]
Hi, 

I was following the instruction TeeRawk posted above for making another fragment but still getting errors.

So far, I understand that `onSwitch` is where I handle when each icon is clicked and `replaceFragment` uses `getSupportFragmentManager().beginTransaction().replace(R.id.content_frame,
contentFragment).commit();` and eventually returns `ContentFragment` object.  

My question is: how do I create a fragment that has its own textView elements. For instance, when BUILDING icon is clicked, it should open a dashboard view with textView and editView elements. 
When ABOUT is clicked, it should open a static text view.

I've tried multiple approaches including: 
**adding a FrameLayout to activity_main.xml but I couldn't create another contentFragment for `getSupportFragmentManager( )` so got errors.
**I created a new Fragment class to extend `ContentFragment` but still got errors w
**Created custom class to extend Fragment and implement `ScreenShotable` and still errors

Any tip / guidance will be super appreciated. Thanks.

**Comment by mohamedebrahim96** [comment]
![App](https://user-images.githubusercontent.com/16405013/29244143-68394f68-7fb1-11e7-9864-dec88cd42660.jpg)

=====================================
This is my fragment code - full project on github
https://github.com/mohamedebrahim96/Whos-in-Space

===========================================
you may also see the live version on google play 
https://play.google.com/store/apps/details?id=com.vacuum.app.whoisinspace
