### ISSUE TITLE
How do I adjust the height of items in navigation?

### ISSUE THREAD

**Issue by KimHunJin** [Yalantis/Side-Menu.Android#56]
Hi. I would like to adjust the item size so that it fits the height of the smartphone, but I do not know how. Please help me.

**Comment by Eddy2017** [comment]
Which size have you used firstly?

**Comment by warko-san** [comment]
Hi, @KimHunJin! Thank you for attention for our side menu. Sorry, but it has no such functionality now, but you can suggest your pull request with it.
