### ISSUE TITLE
How can I import Side-Menu.Android to existed project

### ISSUE THREAD

**Issue by suspectuser** [Yalantis/Side-Menu.Android#60]
![1](https://cloud.githubusercontent.com/assets/25315145/22234483/d81fe60c-e23b-11e6-928c-c1c7c8a450dd.png)

I add lines to build.gradel(Module:app) like this.
And building gradle is completed.

But I cannot use the library, because there aren't generated any library directory.

How can I use this library???

**Comment by warko-san** [comment]
Hi, @suspectuser! After adding the above lines, just refer to classes from the library in your project. Please, checkout the main page of repository to look how to use it in your project. Also, sample app can help you.
