### ISSUE TITLE
İmporting Problem

### ISSUE THREAD

**Issue by HazemEngMuh** [Yalantis/Side-Menu.Android#62]
I could not import these :
  dependencies {
        compile 'com.github.yalantis:Side-Menu.Android:1.0.1'
    }
.
and command:

    repositories {
        maven {
            url "https://jitpack.io"
        }
    }
    dependencies {
        compile 'com.github.ozodrukh:CircularReveal:(latest-release)@aar'
    }
Can you help me ?

**Comment by anam294** [comment]
I am facing the same problem.. Did you find any solution??@HazemEngMuh

**Comment by HazemEngMuh** [comment]
@anam294  I impoted it and it works now .
you can write that .....
apply plugin: 'com.android.application'
repositories {
    maven {
        url "https://jitpack.io"
    }
}
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "************"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile('com.github.ozodrukh:CircularReveal:1.1.1@aar') {
        transitive = true;
    }
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.github.yalantis:Side-Menu.Android:1.0.1'
    compile 'com.android.support:support-v4:25.2.0'
    testCompile 'junit:junit:4.12'
}

**Comment by gabriel-TheCode** [comment]
![io](https://cloud.githubusercontent.com/assets/26333609/24070878/b261b892-0bc5-11e7-86b0-e985e5b9f239.PNG)

Open Android Studio -> Open **Manifest** File

add **uses-sdk tools:overrideLibrary="io.codetail.view"**
**NB**: don't forget to include xmlns:tools="http://schemas.android.com/tools" too, before the _<application>_ tag

**Comment by mohamedebrahim96** [comment]
![App](https://user-images.githubusercontent.com/16405013/29244143-68394f68-7fb1-11e7-9864-dec88cd42660.jpg)

=====================================
This is my fragment code - full project on github
https://github.com/mohamedebrahim96/Whos-in-Space

===========================================
you may also see the live version on google play 
https://play.google.com/store/apps/details?id=com.vacuum.app.whoisinspace

**Comment by vadhmln** [comment]
add like this:
dependencies {
    ...
    implementation ('com.github.ozodrukh:CircularReveal:2.0.1@aar') {
        transitive = true;
    }
    implementation ('com.github.yalantis:Side-Menu.Android:1.0.1') {
        transitive = true;
    }
    ...
}

**Comment by oscarshaitan** [comment]
Same problem Here
my gradle

```
apply plugin: 'com.android.application'

repositories {
    maven {
        url "https://jitpack.io"
    }
}

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.allegorit.sidemenutest"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation ('com.github.ozodrukh:CircularReveal:2.0.1@aar') {
        transitive = true;
    }
    implementation 'com.github.yalantis:Side-Menu.Android:1.0.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

}

```

**Comment by mohamedebrahim96** [comment]
@oscarshaitan 
solved by changing to 

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.vacuum.app.whoisinspace"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 3
        versionName "3.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile 'com.github.yalantis:Side-Menu.Android:1.0.1'
    compile('com.github.ozodrukh:CircularReveal:1.1.1@aar') {
        transitive = true;
    }
  }
```

**Comment by oscarshaitan** [comment]
so the answer its low the target sdk and use compile? and not implementation?
