### ISSUE TITLE
SupportAnimator class not found

### ISSUE THREAD

**Issue by gabriel-TheCode** [Yalantis/Side-Menu.Android#63]
I have correctly make my import like this: import io.codetail.animation.*;
But I have this error;

"Error:(156, 9) error: cannot find symbol class SupportAnimator"

Need help please!!!

**Comment by manenga** [comment]
Use compile 'com.github.ozodrukh:CircularReveal:1.1.1' instead

**Comment by DeveloperHu** [comment]
Thanks@TheBachelor

**Comment by DeveloperHu** [comment]
Thanks @TheBachelor

**Comment by AshnasAshnas** [comment]
thx manegna
