### ISSUE TITLE
Couldn't Find The .aar File???

### ISSUE THREAD

**Issue by syedalinaqi** [Yalantis/Side-Menu.Android#7]
I went here and found no download button for .aar File: https://github.com/Yalantis/Side-Menu.Android/releases/

What happened? 
Plz Give me the link of the library. It Will be a great help.

**Comment by kotya341** [comment]
We are working on this feature

**Comment by syedalinaqi** [comment]
so. How much i would have to wait. Thanks for replying

**Comment by chnsh** [comment]
Can you release the aar file please?

**Comment by syedalinaqi** [comment]
plz release the aar file.

**Comment by kotya341** [comment]
library-debug.aar added please check out
