### ISSUE TITLE
How to replace another fragments?

### ISSUE THREAD

**Issue by nuhkoca** [Yalantis/Side-Menu.Android#72]
Hi,

How can I make to replace a fragment per item of DrawerLayout? It always loads ContentFragment. Thanks!

**Comment by mohamedebrahim96** [comment]
![App](https://user-images.githubusercontent.com/16405013/29244143-68394f68-7fb1-11e7-9864-dec88cd42660.jpg)

=====================================
This is my fragment code - full project on github
https://github.com/mohamedebrahim96/Whos-in-Space

===========================================
you may also see the live version on google play 
https://play.google.com/store/apps/details?id=com.vacuum.app.whoisinspace
